name: DigiteerPocIac
common:
  network:
    useFromStage: dev
    allowExternalAccess: false
  domain:
    useFromStage: dev
    root: lynx.rocks
  service:
    protocol: http
    port: 3000
    maxScale: 2
    targetUtilization: 60
    useSpot: false
  db:
    engine: PostgreSQL
    version: "15.2"
    username: digiteer
    createReader: false
    scaleWithWriter: false
  firewall:
    core: true
    knownBadInputs: true
    ipReputationList: true
    sqlInjection: true
    linuxVulnerabilities: true
    posixVulnerabilities: true
  deployment:
    alarmOnHttp4xx: true
    http4xxThreshold: 10
    taskFilename: task.json
stages:
- name: dev
  service:
    useSpot: true
- name: staging
  domain:
    # Remember to provide different subdomains per stage.
    sub: digiteer-staging
